menu:
  "Meguro.esについて": /about
  "記事一覧": /archives
  "connpass": https://meguroes.connpass.com

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: false

facebook:
google_plus:
twitter: "meguroes"
github:

fancybox: true
google_analytics:
rss:
